# Generated by Django 2.0.7 on 2018-07-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/userImage', verbose_name='头像'),
        ),
    ]
