# Generated by Django 2.1 on 2018-08-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20180718_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trouble',
            name='dear_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
